"""Phase 5 API tests via FastAPI's TestClient.

These exercise the read API against the actual econgraph.db produced by
pipelines 1-4 (it's deterministic, regenerated by `python -m pipeline.build_graph`).
The headline test is the Walmart customer_of derivation: every derived
customer_of edge must mirror a stored supplies edge, with NO customer_of
rows in the DB (CLAUDE.md invariant #2).
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from api import main as api_main
from api import query as q
from schema.store import connect, default_db_path


REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = default_db_path()   # honors ECONGRAPH_DB so this tracks the relocated DB


@pytest.fixture(scope="module", autouse=True)
def configure_app_db():
    """Point the app at the live econgraph.db produced by build_graph."""
    api_main.set_db_path(DB_PATH)
    yield


@pytest.fixture(scope="module")
def client():
    if not DB_PATH.exists():
        pytest.skip(
            "econgraph.db missing; run `python -m pipeline.build_graph` first"
        )
    return TestClient(api_main.app)


# Canonical ids used throughout the tests.
PG_CIK = "cik:0000080424"
WMT_CIK = "cik:0000104169"


# ---------------------------------------------------------------------------
# Smoke + invariant
# ---------------------------------------------------------------------------

def test_health_invariant_zero_customer_of_rows(client):
    r = client.get("/health")
    assert r.status_code == 200
    body = r.json()
    assert body["status"] == "ok"
    # Counts grow as Phase 7 scales out across sectors -- assert only that
    # they're in the expected ranges + that the structural invariant holds.
    # (Hard-coded counts were fragile; they failed every batch.)
    assert body["node_count"] >= 166      # Consumer Staples MVP floor (43 cik + 7 reg + 123 slugs)
    assert body["edge_count"] >= body["core_edge_count"]
    assert body["edge_count"] == body["core_edge_count"] + body["audit_edge_count"]
    # THE INVARIANT: no customer_of rows in the DB. Derivation lives only on read.
    assert body["customer_of_rows_in_db"] == 0


# ---------------------------------------------------------------------------
# /node + alias resolve
# ---------------------------------------------------------------------------

def test_node_by_canonical_id(client):
    r = client.get(f"/node/{PG_CIK}")
    assert r.status_code == 200
    body = r.json()
    assert body["key"] == PG_CIK
    assert "Procter" in body["attributes"]["label"]


def test_node_by_alias_resolves_to_canonical(client):
    # "procter" should hit the alias_normalized = "procter and gamble"
    # via normalize-on-read.
    r = client.get("/node/procter")
    # Direct lookup will only succeed if "procter" is in the alias table as
    # an alias (Phase 3 stored ticker + name + normalized name). Try the
    # ticker, which we know is seeded:
    r2 = client.get("/node/PG")
    assert r2.status_code == 200
    assert r2.json()["key"] == PG_CIK


def test_node_not_found_returns_404(client):
    r = client.get("/node/cik:9999999999")
    assert r.status_code == 404


# ---------------------------------------------------------------------------
# /node/{id}/ego
# ---------------------------------------------------------------------------

def test_pg_ego_contains_walmart_supplies_and_regulators(client):
    r = client.get(f"/node/{PG_CIK}/ego")
    assert r.status_code == 200
    body = r.json()
    assert body["center"] == PG_CIK
    edge_types = {e["attributes"]["type"] for e in body["edges"]}
    assert "supplies" in edge_types
    assert "regulated_by" in edge_types

    # P&G --supplies--> Walmart edge must be present.
    supplies_walmart = [
        e for e in body["edges"]
        if e["attributes"]["type"] == "supplies"
        and e["source"] == PG_CIK
        and e["target"] == WMT_CIK
    ]
    assert len(supplies_walmart) == 1, (
        f"expected exactly one P&G --supplies--> Walmart edge, got {len(supplies_walmart)}"
    )
    # Provenance must be the verbatim filing snippet.
    snippet = supplies_walmart[0]["attributes"]["provenance"]["snippet"]
    assert "Walmart" in snippet

    # Regulators -- P&G is a Consumer Staples Household Products filer.
    reg_targets = {
        e["target"] for e in body["edges"]
        if e["attributes"]["type"] == "regulated_by" and e["source"] == PG_CIK
    }
    assert "regulator:sec" in reg_targets
    assert "regulator:ftc" in reg_targets


# ---------------------------------------------------------------------------
# THE WALMART TEST -- customer_of derivation
# ---------------------------------------------------------------------------

def test_walmart_customer_of_derivation_matches_stored_supplies(client):
    """Walmart's ego with types=customer_of must mirror incoming supplies.

    Specifically: every derived customer_of edge with target=Walmart
    corresponds to a stored supplies edge with target=Walmart (the
    suppliers naming Walmart as their largest customer). Counts equal,
    snippets equal, no customer_of rows in the DB.
    """
    # 1) Pull the derived customer_of edges via the API.
    r = client.get(f"/node/{WMT_CIK}/ego?types=customer_of")
    assert r.status_code == 200
    derived = [
        e for e in r.json()["edges"] if e["attributes"]["type"] == "customer_of"
    ]
    assert derived, "Walmart should be a customer_of someone"
    for e in derived:
        # Each derived edge: Walmart -> supplier. Direction REVERSED from the
        # stored "supplier --supplies--> Walmart" row.
        assert e["source"] == WMT_CIK, f"derived edge source must be Walmart, got {e['source']}"
        assert e["attributes"]["derived"] is True
        assert e["attributes"]["underlying_edge_id"]
        assert e["key"].startswith("derived:customer_of:")

    # 2) Pull the stored supplies edges where Walmart is the target.
    conn = connect(DB_PATH)
    try:
        stored = conn.execute(
            "SELECT * FROM edges WHERE type = 'supplies' AND target = ? AND below_threshold = 0",
            (WMT_CIK,),
        ).fetchall()
    finally:
        conn.close()

    # Same count.
    assert len(derived) == len(stored), (
        f"derived customer_of count ({len(derived)}) must equal stored supplies "
        f"count ({len(stored)}) for Walmart"
    )
    # Same set of (supplier, Walmart) pairs and same snippets.
    derived_pairs = {
        (e["target"], e["attributes"]["provenance"]["snippet"]) for e in derived
    }
    stored_pairs = {(row["source"], row["prov_snippet"]) for row in stored}
    assert derived_pairs == stored_pairs


def test_zero_customer_of_rows_in_db(client):
    """Same as the health check, but asserted directly via SQL."""
    conn = connect(DB_PATH)
    try:
        count = conn.execute(
            "SELECT COUNT(*) FROM edges WHERE type = 'customer_of'"
        ).fetchone()[0]
    finally:
        conn.close()
    assert count == 0


def test_edge_derived_key_resolves_to_underlying_supplies_provenance(client):
    """GET /edge/<derived key> returns the underlying supplies provenance."""
    # Find one derived customer_of key for Walmart.
    ego = client.get(f"/node/{WMT_CIK}/ego?types=customer_of").json()
    derived = next(e for e in ego["edges"] if e["attributes"]["type"] == "customer_of")
    key = derived["key"]
    underlying_id = derived["attributes"]["underlying_edge_id"]

    # Fetch the derived edge by key.
    r = client.get(f"/edge/{key}")
    assert r.status_code == 200
    body = r.json()
    assert body["attributes"]["derived"] is True
    # And the underlying supplies edge.
    r2 = client.get(f"/edge/{underlying_id}")
    assert r2.status_code == 200
    assert r2.json()["attributes"]["type"] == "supplies"
    # Their provenance snippets match.
    assert body["attributes"]["provenance"]["snippet"] == r2.json()["attributes"]["provenance"]["snippet"]


# ---------------------------------------------------------------------------
# /search
# ---------------------------------------------------------------------------

def test_search_procter_resolves_to_pg(client):
    r = client.get("/search", params={"q": "procter"})
    assert r.status_code == 200
    results = r.json()["results"]
    assert results, "expected at least one match for 'procter'"
    assert results[0]["id"] == PG_CIK


def test_search_ticker_resolves(client):
    r = client.get("/search", params={"q": "PG"})
    assert r.status_code == 200
    ids = [hit["id"] for hit in r.json()["results"][:3]]
    assert PG_CIK in ids


# ---------------------------------------------------------------------------
# /subgraph
# ---------------------------------------------------------------------------

def test_subgraph_hops_2_works(client):
    r = client.get("/subgraph", params={"seed": PG_CIK, "hops": 2})
    assert r.status_code == 200
    body = r.json()
    assert body["seed"] == PG_CIK
    assert body["hops"] == 2
    assert len(body["nodes"]) >= 2
    assert len(body["edges"]) >= 1


def test_subgraph_hops_above_max_rejected(client):
    r = client.get("/subgraph", params={"seed": PG_CIK, "hops": 4})
    # FastAPI's Query(le=...) returns 422 for out-of-range; that's an acceptable
    # form of "bounds check failed". 400 also acceptable per the prompt.
    assert r.status_code in (400, 422)


def test_subgraph_truncated_flag_on_huge_query(client):
    # Forcing truncation: very small node cap means even hops=2 trips it.
    conn = connect(DB_PATH)
    try:
        sub = q.bfs_subgraph(
            conn, PG_CIK, hops=2, include_provisional=True, node_cap=5,
        )
    finally:
        conn.close()
    assert sub["truncated"] is True
    assert len(sub["nodes"]) <= 5


# ---------------------------------------------------------------------------
# include_provisional toggle
# ---------------------------------------------------------------------------

def test_include_provisional_toggles_audit_edges(client):
    base = client.get(f"/node/{PG_CIK}/ego", params={"include_provisional": False})
    rich = client.get(f"/node/{PG_CIK}/ego", params={"include_provisional": True})
    assert base.status_code == 200 and rich.status_code == 200
    n_base = len(base.json()["edges"])
    n_rich = len(rich.json()["edges"])
    # Provisional flag must not REDUCE the result; at most expands.
    assert n_rich >= n_base
    # And the rich response should include below_threshold=true edges if PG's
    # filing named any provisional slug competitors. Sanity-check there's at
    # least one such filer in our dataset (Constellation Brands etc.):
    rich_const = client.get(
        "/node/cik:0000016918/ego",
        params={"include_provisional": True, "types": "competes_with"},
    ).json()
    has_audit = any(
        e["attributes"]["below_threshold"]
        for e in rich_const["edges"]
        if e["attributes"]["type"] == "competes_with"
    )
    assert has_audit, "expected at least one audit competes_with edge for Constellation Brands"


def test_provisional_excluded_by_default(client):
    """The default ego query for a heavy-audit filer must omit below_threshold edges."""
    r = client.get(
        "/node/cik:0000016918/ego",  # Constellation Brands has many slug competes_with
        params={"types": "competes_with"},
    )
    assert r.status_code == 200
    flags = [e["attributes"]["below_threshold"] for e in r.json()["edges"]]
    assert all(f is False for f in flags)


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

def test_cors_header_present_for_localhost_origin(client):
    # FastAPI's CORS middleware sets the header only when an Origin header is
    # supplied. Preflight not needed for GET; check the actual GET response.
    r = client.get(
        "/health",
        headers={"Origin": "http://localhost:5173", "Accept": "application/json"},
    )
    assert r.status_code == 200
    assert r.headers.get("access-control-allow-origin") in (
        "http://localhost:5173", "*",
    )


# ---------------------------------------------------------------------------
# POST /impact/stream (NDJSON)
# ---------------------------------------------------------------------------
import re as _re


def _fake_llm_for_stream(prompt: str) -> str:
    """Deterministic fake LLM: echo verdicts derived from the prompt.

    Emits VALID JSON (json.dumps) — the engine's strict json.loads rejects
    single-quoted strings, so Python `!r` formatting must NOT be used here.
    """
    if "Extract ONLY investable companies" in prompt:
        return "[]"
    if "Pick the ONE node" in prompt:
        m = _re.search(r"^\s*(\S+)\s*\|", prompt, _re.MULTILINE)
        nid = m.group(1) if m else None
        return json.dumps(
            {"node_id": nid, "direction": "negative", "magnitude": 0.9, "reasoning": "t"}
        )
    if "propagating a news shock" in prompt:
        # Scope the id scan to the candidate section so we don't echo seed lines.
        cand_section = prompt.split("CANDIDATES at hop", 1)[-1]
        ids = _re.findall(r"^\s{2}(\S+)\s*\|", cand_section, _re.MULTILINE)
        return json.dumps(
            [
                {"node_id": i, "direction": "negative", "magnitude": 0.5, "reasoning": "t"}
                for i in ids
            ]
        )
    if "refining impact assessments" in prompt:
        ids = _re.findall(r"^NODE:\s*(\S+)\s*\(", prompt, _re.MULTILINE)
        return json.dumps(
            [
                {"node_id": i, "direction": "negative", "magnitude": 0.9, "reasoning": "t"}
                for i in ids
            ]
        )
    return ""


def test_impact_stream_ndjson(client, monkeypatch):
    from api import impact as impact_mod
    monkeypatch.setattr(impact_mod, "_llm_call", _fake_llm_for_stream)
    monkeypatch.setattr(impact_mod, "MAX_FRONTIER", 9999)
    r = client.post("/impact/stream", json={"text": "global crude oil supply shock"})
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("application/x-ndjson")
    lines = [ln for ln in r.text.splitlines() if ln.strip()]
    events = [json.loads(ln) for ln in lines]
    assert events[0]["event"] == "seeds"
    assert events[-1]["event"] == "done"
    assert "impacts" in events[-1]["result"]


def test_impact_stream_forwards_seed_hint(client, monkeypatch):
    # "Sharpen with Claude" on a commodity/region node passes seed_hint_id so the
    # trace grounds at the known node instead of failing Company-only extraction.
    from api import impact as impact_mod
    captured = {}

    def fake_stream(text, *, conn, provider=None, seed_hint_id=None, context=None, **kw):
        captured["seed_hint_id"] = seed_hint_id
        captured["context"] = context
        yield {"event": "seeds", "seeds": []}
        yield {"event": "done", "result": {"impacts": [], "seed": None}}

    monkeypatch.setattr(impact_mod, "run_impact_stream", fake_stream)
    r = client.post("/impact/stream",
                    json={"text": "cocoa squeeze", "seed_hint_id": "commodity:cocoa",
                          "context": "[involves: Nestle | $2B | negative tone]"})
    assert r.status_code == 200
    assert captured["seed_hint_id"] == "commodity:cocoa"
    assert captured["context"] == "[involves: Nestle | $2B | negative tone]"

    # Absent hint/context → None (on-demand search box behavior is unchanged).
    r2 = client.post("/impact/stream", json={"text": "cocoa squeeze"})
    assert r2.status_code == 200 and captured["seed_hint_id"] is None and captured["context"] is None


def test_usage_endpoint_shape_and_validation(client):
    r = client.get("/usage?granularity=day&days=7")
    assert r.status_code == 200
    d = r.json()
    assert d["granularity"] == "day" and d["days"] == 7 and isinstance(d["buckets"], list)
    for b in d["buckets"]:
        assert set(b) >= {"bucket", "input_tokens", "output_tokens", "cache_read_tokens", "cost_usd", "calls"}
    assert client.get("/usage?days=9999").json()["days"] == 365    # clamped high
    assert client.get("/usage?days=0").json()["days"] == 1         # clamped low
    assert client.get("/usage?granularity=minute").status_code == 400   # bad granularity


def test_impact_stream_requires_text(client):
    r = client.post("/impact/stream", json={"text": "   "})
    assert r.status_code == 400


def test_impact_stream_rejects_bad_provider(client):
    r = client.post("/impact/stream", json={"text": "oil", "provider": "gpt4"})
    assert r.status_code == 400
