Integrated Oil & Gas:
- carbon-credits
- crude-oil
- hydrogen
- natural-gas
- sulfur
Oil & Gas Exploration & Production:
- crude-oil
- natural-gas
- silica-sand
Oil & Gas Refining & Marketing:
- carbon-credits
- crude-oil
- ethylene
- hydrogen
- propylene
- sulfur
Oil & Gas Storage & Transportation:
- crude-oil
- natural-gas
Oil & Gas Equipment & Services:
- molybdenum
- silica-sand
- steel
Electric Utilities:
- carbon-credits
- coal
- hydrogen
- natural-gas
- uranium
- water
Multi-Utilities:
- carbon-credits
- coal
- hydrogen
- natural-gas
- uranium
- water
Independent Power Producers & Energy Traders:
- carbon-credits
- coal
- natural-gas
- uranium
- zirconium
Gas Utilities:
- natural-gas
Water Utilities:
- chlorine
- salt
- water
Steel:
- carbon-credits
- chromium
- coal
- iron-ore
- limestone
- manganese
- molybdenum
- nickel
- niobium
- vanadium
- zinc
Copper:
- copper
Gold:
- gold
Commodity Chemicals:
- ammonia
- caustic-soda
- chlorine
- crude-oil
- ethylene
- methanol
- natural-gas
- phosphate
- propylene
- salt
- soda-ash
Specialty Chemicals:
- ammonia
- caustic-soda
- chlorine
- ethylene
- mercury
- methanol
- palladium
- platinum
- propylene
- sulfuric-acid
Industrial Gases:
- ammonia
- helium
- hydrogen
- nitrogen-fertilizer
Fertilizers & Agricultural Chemicals:
- ammonia
- nitrogen-fertilizer
- phosphate
- potash
- sulfuric-acid
Construction Materials:
- bauxite
- carbon-credits
- cement
- gypsum
- limestone
- sand-gravel
- soda-ash
Paper & Plastic Packaging Products & Materials:
- paper
- pet
- polyethylene
- polypropylene
- pulp
Metal, Glass & Plastic Containers:
- aluminum
- pet
- polyethylene
- polypropylene
- silica-sand
- soda-ash
- steel
- tin
Automobile Manufacturers:
- aluminum
- antimony
- cobalt
- copper
- dysprosium
- graphite
- lead
- lithium
- lithium-carbonate
- magnesium
- manganese
- manganese-sulfate
- nickel
- nickel-sulfate
- palladium
- platinum
- polypropylene
- rhodium
- rubber
- steel
- synthetic-rubber
- vanadium
- zinc
Automotive Parts & Equipment:
- aluminum
- copper
- rubber
- steel
- synthetic-rubber
Automotive Retail: []
Passenger Airlines:
- aluminum
- biodiesel
- carbon-credits
- crude-oil
- titanium
Rail Transportation:
- biodiesel
- coal
- crude-oil
- steel
Cargo Ground Transportation:
- biodiesel
- crude-oil
- natural-gas
Air Freight & Logistics:
- biodiesel
- carbon-credits
- crude-oil
Passenger Ground Transportation:
- crude-oil
Construction & Engineering:
- aluminum
- cement
- copper
- lumber
- pvc
- sand-gravel
- steel
Construction Machinery & Heavy Transportation Equipment:
- aluminum
- copper
- rubber
- steel
Industrial Machinery & Supplies & Components:
- aluminum
- copper
- steel
Agricultural & Farm Machinery:
- copper
- rubber
- steel
Heavy Electrical Equipment:
- aluminum
- copper
- dysprosium
- silicon
- steel
Electrical Components & Equipment:
- aluminum
- copper
- silicon
Industrial Conglomerates:
- aluminum
- copper
- silicon
- steel
Building Products:
- aluminum
- antimony
- cement
- copper
- gypsum
- lumber
- pvc
- silica-sand
- steel
- synthetic-rubber
- zinc
Homebuilding:
- cement
- copper
- gypsum
- lumber
- pvc
- sand-gravel
- steel
Environmental & Facilities Services: []
Trading Companies & Distributors: []
Distributors: []
Aerospace & Defense:
- aluminum
- antimony
- beryllium
- copper
- helium
- magnesium
- molybdenum
- nickel
- niobium
- rare-earths
- steel
- tantalum
- titanium
- tungsten
- vanadium
- zirconium
Semiconductors:
- copper
- gallium
- germanium
- gold
- graphite
- helium
- indium
- neodymium
- rare-earths
- silicon
- silver
- tellurium
- tin
Semiconductor Materials & Equipment:
- gallium
- germanium
- helium
- hydrogen
- silicon
- tellurium
Technology Hardware, Storage & Peripherals:
- aluminum
- cobalt
- copper
- gold
- graphite
- lithium
- lithium-carbonate
- neodymium
- silicon
Communications Equipment:
- copper
- germanium
- gold
- neodymium
- rare-earths
- silicon
- silver
- tantalum
Consumer Electronics:
- cobalt
- copper
- gold
- indium
- lithium
- lithium-carbonate
- magnesium
- neodymium
- silicon
Electronic Components:
- copper
- gold
- silicon
- silver
- tantalum
- tin
Electronic Equipment & Instruments:
- copper
- gold
- silicon
Electronic Manufacturing Services:
- copper
- gold
- silicon
- tantalum
Technology Distributors: []
Computer & Electronics Retail: []
Application Software: []
Systems Software: []
Internet Services & Infrastructure:
- copper
- silicon
IT Consulting & Other Services: []
Data Processing & Outsourced Services: []
Interactive Media & Services:
- copper
- silicon
Interactive Home Entertainment:
- copper
- silicon
Data Center REITs:
- aluminum
- copper
- silicon
- water
Telecom Tower REITs:
- copper
- steel
Packaged Foods & Meats:
- barley
- beef
- chicken
- cocoa
- corn
- dairy
- eggs
- fish
- oats
- palm-oil
- paper
- pet
- polyethylene
- pork
- rapeseed
- rice
- salt
- sorghum
- soybeans
- sugar
- sunflower-oil
- wheat
Soft Drinks & Non-alcoholic Beverages:
- aluminum
- coffee
- corn
- ethanol
- orange-juice
- pet
- sugar
- tea
- water
Brewers:
- aluminum
- barley
- sorghum
- sugar
- water
Distillers & Vintners:
- corn
- sorghum
- sugar
- water
- wheat
Tobacco:
- tobacco
Household Products:
- caustic-soda
- cotton
- ethylene
- palm-oil
- polypropylene
- pulp
- salt
- soda-ash
Personal Care Products:
- bismuth
- cotton
- ethanol
- ethylene
- palm-oil
- polyethylene
- rapeseed
- sugar
- sunflower-oil
Food Distributors:
- beef
- chicken
- dairy
- eggs
- fish
- pork
Food Retail:
- beef
- chicken
- cocoa
- coffee
- corn
- dairy
- eggs
- fish
- oats
- orange-juice
- pork
- rice
- salt
- tea
- wheat
Agricultural Products & Services:
- corn
- palm-oil
- rapeseed
- rice
- soybeans
- sugar
- sunflower-oil
- wheat
Apparel, Accessories & Luxury Goods:
- cotton
- diamond
- leather
- rubber
- silk
- synthetic-rubber
- wool
Apparel Retail: []
Footwear:
- cotton
- leather
- rubber
- synthetic-rubber
Restaurants:
- beef
- chicken
- cocoa
- coffee
- corn
- dairy
- eggs
- fish
- oats
- palm-oil
- pork
- rice
- sorghum
- soybeans
- sugar
- sunflower-oil
- tea
- wheat
Consumer Staples Merchandise Retail: []
Broadline Retail: []
Home Improvement Retail: []
Homefurnishing Retail: []
Other Specialty Retail: []
Casinos & Gaming: []
Hotels, Resorts & Cruise Lines:
- crude-oil
Leisure Products:
- aluminum
- lumber
- rubber
Specialized Consumer Services: []
Consumer Finance: []
Pharmaceuticals:
- bismuth
- ethanol
- palladium
- platinum
- sulfuric-acid
- water
Biotechnology:
- water
Life Sciences Tools & Services: []
Health Care Equipment:
- helium
- silicon
- steel
- titanium
Health Care Supplies:
- cotton
- paper
- pet
- polyethylene
- pulp
- pvc
- silver
Health Care Distributors: []
Health Care Facilities: []
Health Care Services:
- chlorine
Health Care Technology: []
Managed Health Care: []
Health Care REITs: []
Movies & Entertainment: []
Advertising: []
Publishing:
- paper
- pulp
Broadcasting: []
Cable & Satellite: []
Integrated Telecommunication Services:
- copper
- silicon
Wireless Telecommunication Services:
- copper
- dysprosium
- neodymium
- silicon
Diversified Banks: []
Regional Banks: []
Asset Management & Custody Banks: []
Investment Banking & Brokerage: []
Financial Exchanges & Data: []
Transaction & Payment Processing Services: []
Multi-Sector Holdings: []
Insurance Brokers: []
Property & Casualty Insurance: []
Life & Health Insurance: []
Reinsurance: []
Multi-line Insurance: []
Multi-Family Residential REITs: []
Single-Family Residential REITs: []
Industrial REITs: []
Retail REITs: []
Office REITs: []
Self-Storage REITs: []
Other Specialized REITs: []
Hotel & Resort REITs: []
Timber REITs:
- hardwood
- lumber
- pulp
Real Estate Services: []
Diversified Support Services: []
Research & Consulting Services: []
Human Resource & Employment Services: []
